### ISSUE TITLE
Package import does not exist.

### ISSUE THREAD

**Issue by sanskritkm** [donaldamadi/multi-image-viewer#3]
Hello,

When I try to import package it said as below screenshot.

<img width="739" alt="image" src="https://github.com/donaldamadi/multi-image-viewer/assets/17005582/5d3123c0-285a-4371-be61-9be6223a545a">

**Comment by donaldamadi** [comment]
Hi @kdamsmt, can you confirm you got this error after successfully running the ```flutter pub get``` command after adding the package to your pubspec.yaml file?

**Comment by donaldamadi** [comment]
Closing the issue as there were no interactions on it for a while
